name: deploy to VPS
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /${{ secrets.USERNAME }}/telegram_bot_rachel;
          git pull -f;
          source /${{ secrets.USERNAME }}/.nvm/nvm.sh;
          nvm install 16;
          nvm use 16;
          yarn install;
          export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }};
          export MASTODON_ACCESS_TOKEN=${{ secrets.MASTODON_ACCESS_TOKEN }};
          export TELEGRAM_CHANNEL_ID=${{ secrets.TELEGRAM_CHANNEL_ID }};
          kill -9 `ps -ef | grep "nodemon app.js" | grep -v grep | awk '{print $2}'`;
          nohup yarn nodemon app.js </dev/null >> logs/logs.txt 2>&1 &